//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DolphinWebXplorer2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DolphinWebXplorer2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foldericon {
            get {
                object obj = ResourceManager.GetObject("foldericon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foldericond {
            get {
                object obj = ResourceManager.GetObject("foldericond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap messagebox_info {
            get {
                object obj = ResourceManager.GetObject("messagebox_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap osubf {
            get {
                object obj = ResourceManager.GetObject("osubf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ouplo {
            get {
                object obj = ResourceManager.GetObject("ouplo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run {
            get {
                object obj = ResourceManager.GetObject("run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap screen {
            get {
                object obj = ResourceManager.GetObject("screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var shs = new (function () {
        ///    var xmlhttp = new XMLHttpRequest();
        ///    var byId = function (name) {
        ///        return document.getElementById(name);
        ///    }
        ///    var sfifo = [];
        ///    var sending = false;
        ///    var send = function (code, cmd, important) {
        ///        if (sending) {
        ///            if (important)
        ///                sfifo.push(cmd);
        ///            return;
        ///        }
        ///        sending = true;
        ///        if (cmd == null) {
        ///            cmd = sfifo.shift();
        ///        }
        ///        xmlhttp.open(&quot;GET&quot;, &quot;$screencmd? [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShScreen {
            get {
                return ResourceManager.GetString("ShScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html{
        /// background:#BBBBBB;
        ///}
        ///
        ///body{
        /// margin:0 auto 0 auto;
        /// max-width: 900px;
        /// background:white;
        /// box-shadow: 0 0 5px;
        /// padding:2px;
        /// font-family:verdana;
        /// font-size:12px;
        /// padding:0;
        ///}
        ///
        ///#head{
        /// height:68px;
        /// background:#F5F6F7 url(/·logo) 20px 20px no-repeat;
        /// padding:10px 10px 10px 80px;
        /// font-family: verdana;
        /// font-size:25px;
        /// border-bottom: solid 1px #DADBDC;
        /// box-shadow: 0 3px 2px -2px gray;
        /// position:relative;
        ///}
        ///#head a{
        /// color:black;
        /// text-decoration:none;
        ///}
        ///#head a:hover [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string site {
            get {
                return ResourceManager.GetString("site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html{
        /// background: #222;
        /// height: 100%;
        ///}
        ///
        ///body{
        /// display: table;
        /// margin: 0 auto;
        /// height: 100%;
        ///}
        ///
        ///div#ctt {
        /// display: table-cell;
        /// vertical-align: middle;
        /// height: 100%;
        ///}
        ///
        ///div#main {
        /// background: #FFF;
        /// box-shadow: 0 2px 7px #999;
        /// border: 0px;
        /// border-radius:4px;
        /// font-family:verdana;
        /// font-size:12px;
        /// padding:0;
        /// overflow:hidden;
        ///}
        ///
        ///div#frm {
        /// padding:10px;
        ///}
        ///
        ///img#scr {
        ////*
        /// max-width:100%;
        /// max-height:100%;
        ///*/
        ///}.
        /// </summary>
        internal static string siteblack {
            get {
                return ResourceManager.GetString("siteblack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon sunfishWebServer {
            get {
                object obj = ResourceManager.GetObject("sunfishWebServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sws {
            get {
                object obj = ResourceManager.GetObject("sws", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap t_delete {
            get {
                object obj = ResourceManager.GetObject("t_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap t_execute {
            get {
                object obj = ResourceManager.GetObject("t_execute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload {
            get {
                object obj = ResourceManager.GetObject("upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
